### ISSUE TITLE
Answer failing, can dial succesfully

### ISSUE THREAD

**Issue by tomlister** [emiago/sipgox#11]
Hi,

This is a great library.
I'm able to register with my pbx, dial another sip phone on my pbx, decode g.711 and encode it into a wav file.

However, I'm trying to get my program to answer calls instead of dialling.
I've set up the `phone.Answer` function instead of dial but when I phone the program's extension I can see lot of logs coming in but the call seems to fail and no RTP stream begins.

Log snippet (many occurrences of these):
```
{"level":"warn","caller":"Server","time":"2024-06-11T20:11:10+10:00","message":"SIP request handler not found"}
{"level":"debug","caller":"transportlayer","network":"udp","addr":"192.168.0.229:5060","time":"2024-06-11T20:11:10+10:00","message":"getting connection"}
{"level":"debug","src":"192.168.0.113:65034","dst":"192.168.0.113:65034","ref":910,"time":"2024-06-11T20:11:10+10:00","message":"UDP reference decrement"}
{"level":"debug","caller":"transactionLayer","time":"2024-06-11T20:11:10+10:00","message":"Server transaction terminating"}
{"level":"debug","caller":"transactionLayer","tx":"z9hG4bKPj7c872d6d-84de-48b8-ac31-455ea6e34e7d__192.168.0.229__5060__INVITE","time":"2024-06-11T20:11:10+10:00","message":"Server transaction destroyed"}

```

Any idea why this could be happening?

**Comment by emiago** [comment]
Hi @tomlister 

I can not see anything here. all looks normal. 
gophone uses same code, maybe try first that tool and do SIP trace to compare.

**Comment by tomlister** [comment]
Thanks mate, I've realized where my error is.
Closing.

**Comment by jlnrrg** [comment]
@tomlister If you could also provide the solution to your error, it would help me greatly 😅.
