### ISSUE TITLE
Wrong time for reregister timer

### ISSUE THREAD

**Issue by Noksa** [emiago/sipgox#12]
Hi.

We've found that this line (https://github.com/emiago/sipgox/blob/main/register_transaction.go#L131) doesn't follow RFC (https://datatracker.ietf.org/doc/html/rfc3261#section-10.2.4)

Quote:
```
 The UA then issues a REGISTER request for each of its bindings before the expiration interval has elapsed.
```

In case of `ticker := time.NewTicker(time.Duration(expiry) * time.Second)` there always be a race and if we use TCP, connection can be closed from server side if UA wasn't so fast

One of possible solutions can be renew registration when 80% of expiration time has elapsed:
```
ticker := time.NewTicker(time.Duration(expiry.Seconds()*0.8) * time.Second)
```

I understand that it is just an example but if people blindly copy it, they may encounter issues and spend time to find the cause

**Comment by emiago** [comment]
Thanks for reporting, this will be handled in new project and probably sipgox will be refactored

**Comment by emiago** [comment]
hi @Noksa fixed in diago by providing retry interval. I will not invest more time here. 
Switch to diago pls.
