### ISSUE TITLE
Saving RTP to Audio File

### ISSUE THREAD

**Issue by jlnrrg** [emiago/sipgox#13]
Hello Emiago,
I am very lucky to have found your sipgo ecosystem ☺️.

With the help of your [echome example](https://github.com/emiago/sipgox/blob/main/echome/echouas/main.go) I was able to build a simple program which saves the payload onto the server's disk. The resulting wav file is of cause not playable, as the payload consists of RTP bytes.

Unfortunately I did not find out how I can transform the transmitted RTP bytes into a format like e.g. PCM bytes.
I noticed that in your media package you have a [test](https://github.com/emiago/media/blob/main/rtp_packet_reader_test.go) for the RTPReader and mention different Formats within the `MediaSession` Formats, thus my assumption that maybe the encoding is a lot different than I expected.

If you could give me some pointers where to look, I would be very fortunate.
(Sorry in advance, if my message does not correspond to the issue type you would like to discuss on here)

Thanks
Jlnrrg

**Comment by jlnrrg** [comment]
By looking a little bit further through the previous commits of the [media package](https://github.com/emiago/media), I found out that you recently created a [WavWriter](https://github.com/emiago/media/blob/main/audio/wav_writer.go) which (just from the name) seems to be what need 😅 .

I tried to just pass the payload like this:

```go
import (
	"fmt"
	"os"

	"github.com/emiago/media"
	"github.com/emiago/sipgo"
	"github.com/emiago/sipgox"
	"github.com/pion/rtp"
	mediaAudio "github.com/emiago/media/audio"
)
...

p := rtp.Packet{}
... // fill p with data like in echome

file, _ := os.Create("./test.wav")
writer := mediaAudio.NewWavWriter(file, media.RTPBufSize)
n, writeErr := writer.Write(p.payload)
```


But running it like this creates a panic error:
```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x354961d]

goroutine 35 [running]:
github.com/emiago/media/audio.(*WavWriter).Write(0xc000296de0, {0xc00029e000, 0xa0, 0xa0})
        /Users/julian/go/pkg/mod/github.com/emiago/media@v0.2.0/audio/wav_writer.go:69 +0x17d
```

**Comment by emiago** [comment]
Hi @jlnrrg thanks for feedback.
Everything now is moved to [diago](https://github.com/emiago/diago) framework. This will obsolete sipgox and have more advanced media package. If you want to find out more what is cooking contact me on email. 
Recording is something that will be part of this, but maybe as seperate module.

Will close this issue.

**Comment by jlnrrg** [comment]
For everyone who arrives here after me:
The solution is to check the encoding of the rtp sent. 
In the [rtp_session_test.go](https://github.com/emiago/media/blob/1fbb7d85470f093505d492def9ee1ac0a102db3d/rtp_session_test.go#L21) you can see that it is either `ALAW` or `ULAW`. In the [codec.go](https://github.com/emiago/media/blob/1fbb7d85470f093505d492def9ee1ac0a102db3d/codec.go#L42) you can find the method `codecFromPayloadType` which you can use to parse the payloadType from the rtp payload.

In my case it resulted in `ALAW`.

Using this information you can use a package like [g711](https://github.com/zaf/g711) to decode Alaw.
The bytes you get now are in the following audio settings (like in the [WavWriter](https://github.com/emiago/media/blob/1fbb7d85470f093505d492def9ee1ac0a102db3d/audio/wav_writer.go#L21)):
- SampleRate: 8000
- Bit Depth: 16
- Channels: 1
