### ISSUE TITLE
Dial with your own Caller ID?

### ISSUE THREAD

**Issue by 0xffffa** [emiago/sipgox#15]
I would like to have my own CNAM values/Change my caller id, are you able to add functionality to do this or accept a pull request?

**Comment by emiago** [comment]
hi @0xffffa , if this is for phone, it is already doable. It is on UA creating. Otherwise I suggest going with https://github.com/emiago/diago. It is small migration and you can have this via Header for now. 
Helpers will be soon available, like handling anonymous as well

**Comment by 0xffffa** [comment]
I just wanted to say thank you for releasing open source projects like this and still being active with any questions users may have. People like you are the reason we are where we are with technology and I am grateful for the free flow of information.

Thank you!
