### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by chiefMarlin** [emiago/sipgox#3]
Hi
Do you have any examples of audio playback ?

Thanks

**Comment by emiago** [comment]
@chiefMarlin right now not opensource but `gophone` tool has audio/speaker/mic playback. I developed this only for personal use, still showing as demo. 
What is your use case?

**Comment by chiefMarlin** [comment]
I just wanted to play around with injecting audio into the channel, eg call extension and play audio

**Comment by emiago** [comment]
Ok for start you can try looking this 
```
func (d *DialogClientSession) MediaStream(s MediaStreamer) error {
	return s.MediaStream(d.MediaSession)
}
```

You need to implement `MediaStream` which basically calls this when MediaSession is setup (RTP/RTCP) and Formats.

Same approach is used by `gophone` , rest is now basicaly writing packets, but this I would really need to take time to make available. 

I will keep this ticket open as reminder.

**Comment by simobgl** [comment]
Would be very useful to have the gophone source, no matter its current state. I'm a newbie on SIP and there's a lot to digest. Having a working example of what I specifically need (transcribe, audio answer, etc) would help.

**Comment by emiago** [comment]
Hi @simobgl. Welcome. 
Thanks for comment, there is ofcourse missing gap with media on this project, but it is not really my focus. 
Anyway I could say that some more examples on sipgox could be added or some media wrappers.  
Stay tuned and support sipgo
