### ISSUE TITLE
how to add rport in phone register?

### ISSUE THREAD

**Issue by yangjuncode** [emiago/sipgox#4]
i want to use sipgo and test it with sipgox, but sipgox has no rport set in register so in nat network, the contact is not correct, and i can not recv freeswitch message.

i am using linphone and it can register ok. 

the difference is linphone send register with rport first, freeswitch send 200, then linphone use the rport info fill the contact head and send second register and got 200, then register is ok.

**Comment by emiago** [comment]
hi @yangjuncode 
I guess this is more for support on 
https://datatracker.ietf.org/doc/html/rfc3581

which is not yet fully supported. 
Lets keep ticket open. It is on my list

**Comment by emiago** [comment]
Added support for client NAT and rport 
https://github.com/emiago/sipgo/commit/1e42b52a547b694a43ad3d882066a203c76d15a8

**Comment by emiago** [comment]
@yangjuncode Added NAT support. pls rebase.

**Comment by yangjuncode** [comment]
thank you very much, works!
