### ISSUE TITLE
how to force phone only using tcp for sip? 

### ISSUE THREAD

**Issue by yangjuncode** [emiago/sipgox#5]
currently it seems sipgo only use udp,  thanks for all your info!

the reason i want to use tcp is i need to transfer large message than mtu, udp is not fit.

```
{"level":"debug","caller":"transaction.Layer","error":"size of packet larger than MTU","req":"MESSAGE sip:1000@119.23.43.233:7060 SIP/2.0","time":"2023-12-15T14:43:35+08:00","message":"Fail to write request on init"}
```

**Comment by emiago** [comment]
no all protocols are supported. It can be set by recipient header parameter or by setting `msg.SetTransport` on message.
