### ISSUE TITLE
media wrappers for Speaker/Microphone

### ISSUE THREAD

**Issue by emiago** [emiago/sipgox#7]
Based on https://github.com/emiago/sipgox/issues/3
expose some functionality and provide examples. 

There should not be C binding in lib but can be shared as example

**Comment by ahmed-troido** [comment]
Are you still working on these samples, cuz I'm waiting for these examples?

**Comment by emiago** [comment]
hi @ahmed-troido. Unfortunatelly my time is limited and now there is work on new media library design where I am open sourcing some stuff.  There are just more important projects on my queue.

https://github.com/emiago/media

If you really need this, we can push this via consulting. You can contact on mail for more.

**Comment by emiago** [comment]
No additional work here will be done. 
All phone related is moved now to diago project.
