### ISSUE TITLE
Error address already in use when set RTPPortStart and RTPPortEnd

### ISSUE THREAD

**Issue by muchlisegeroo** [emiago/sipgox#9]
Hi,
i got an error message when setting RTPPortStart and RTPPortEnd.
2024-05-13T10:41:42+07:00 | ERROR | ../../internal/service/voip_impl.go:79 > Error dialing number error="listen udp 100.94.74.20:5120: bind: address already in use"

here is my code.
![image_2024-05-13_110437239](https://github.com/emiago/sipgox/assets/157561085/662a25b5-5686-4c0a-93d1-fc35dc64a8a1)

I think the problem is here, the port is already listening when the retry process occurs.
![image_2024-05-13_105747957](https://github.com/emiago/sipgox/assets/157561085/804705c2-2ad1-4f2c-bcd6-03b3ad0894e9)

In version 0.7.0, this problem does not occur.

Thanks.

**Comment by emiago** [comment]
@muchlisegeroo aah forgot retry. Will fix

**Comment by emiago** [comment]
@muchlisegeroo pls check latest commit. I will create fix release after

**Comment by muchlisegeroo** [comment]
Nice, thanks.
